apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: synchro-landing-pages
  labels:
    app: synchro-landing-pages
spec:
  replicas: 2
  selector:
    matchLabels:
      app: synchro-landing-pages
  template:
    metadata:
      labels:
        app: synchro-landing-pages
    spec:
      containers:
        - name: synchro-landing-pages
          image:
          ports:
          - containerPort: 5000
            name: app-http
          command: ["/home/flask/app/docker_prod_boot.sh"]
          envFrom:
          - configMapRef:
            name: anatha-config
          env:
            - name: MYSQL_URL
              valueFrom: 
                secretKeyRef:
                  name: synchro-secrets
                  key: MYSQL_URL
            - name: RECHARGE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: synchro-secrets
                  key: RECHARGE_CLIENT_SECRET