apiVersion: v1
kind: Secret
metadata:
  name: synchro-secrets
type: Opaque
stringData:
  MYSQL_URL: mysql://synchro:u4A8JWbGrV@104.197.253.0/synchro_db
  RECHARGE_CLIENT_SECRET: f5eb219997e2bef6359be42c0229aca7780718f56aa6f9bbdf5351373e178843
