apiVersion: v1
kind: Service
metadata: 
  name: synchro-load-balancer
spec:
  selector: 
    app: synchro-landing-pages
  type: LoadBalancer
  ports:
  - port: 80
    name: http
    targetPort: 5000
  - port: 443
    name: https
    targetPort: 5000