# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc;
fi;

PS1='\[\e[0;32m\]\u\[\e[m\] \[\e[1;34m\]\w\[\e[m\] \[\e[1;32m\]\$\[\e[m\] \[\e[1;37m\]'

source ~/synchro_venv/bin/activate;
export SYNCHRO_ENV="LOCAL"
